apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  labels:
    run: web
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: k8s.maslick.ru
      http:
        paths:
          - path: /hi
            backend:
              serviceName: web
              servicePort: 8080